apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: c368team03devapi
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: production-support-course
  filterTags:
    pattern: '^c368team03api-dev-(?P<ts>.*)'
    extract: '$ts'
  policy:
     numerical:
      order: asc
