apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: orderbook
  namespace: c368-team03-dev
spec:
  jobName: blackbox
  interval: 60s
  scrapeTimeout: 30s
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.prometheus:9115
    scheme: http
  targets:
    staticConfig:
      static:
        - http://c368team03dev.computerlab.online/stub_status

